-- Library room reservation - demo data
--
-- Run after database/schema.sql:
--
--   mysql -u root -p < database/seed.sql
--
-- No user accounts are seeded. Passwords are bcrypt hashes generated by the
-- application, so accounts are created by registering through the UI; the
-- README explains how to promote one to lecturer or staff afterwards.

USE `library_room_reservation`;

INSERT INTO `time_slot` (`slot_id`, `start_time`, `end_time`) VALUES
  (1, '08:00:00', '10:00:00'),
  (2, '10:00:00', '12:00:00'),
  (3, '13:00:00', '15:00:00'),
  (4, '15:00:00', '17:00:00');

-- The image column holds a filename. These files ship in public/images, so the
-- room cards render straight after a clone. Images uploaded later by staff are
-- written to public/uploads instead.
INSERT INTO `room` (`room_name`, `room_status`, `capacity`, `location`, `description`, `image`) VALUES
  ('Study Room A',      1,  6, 'Library, 2nd floor', 'Quiet space with desks and power outlets for focused work.', 'StudyRoom1.png'),
  ('Study Room B',      1,  5, 'Library, 2nd floor', 'Small group room suited to pair work.',                      'StudyRoom2.png'),
  ('Study Room C',      1,  6, 'Library, 3rd floor', 'Calm area for individual or group study.',                   'StudyRoom3.png'),
  ('Study Room D',      1,  8, 'Library, 3rd floor', 'Larger study room with a whiteboard.',                       'StudyRoom4.jpg'),
  ('Multimedia Room A', 1, 11, 'Library, 1st floor', 'Equipped with AV tools for presentations and media work.',   'MultimediaRoom1.png'),
  ('Multimedia Room B', 1, 15, 'Library, 1st floor', 'Tech-ready space for presentations.',                        'MultimediaRoom2.png'),
  ('Multimedia Room C', 1, 16, 'Library, 1st floor', 'Interactive room for producing digital content.',            'MultimediaRoom3.jpg'),
  ('Meeting Room A',    1, 10, 'Library, 4th floor', 'Meeting table and ergonomic seating for long sessions.',     'MultimediaRoom4.png'),
  ('Meeting Room B',    1,  9, 'Library, 4th floor', 'Versatile room with audiovisual equipment.',                 'Room1.jpg'),
  ('Meeting Room C',    0, 10, 'Library, 4th floor', 'Currently offline for maintenance.',                         'Room.jpg');
